# Generated by Django 5.0.7 on 2024-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_bloodstock_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
