# Generated by Django 5.0.7 on 2024-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_blooddonate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
