# Generated by Django 5.0.7 on 2024-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_blooddonate_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
    ]
