# Generated by Django 5.0.7 on 2024-09-20 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_bloodrequest_city_bloodrequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_requested',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='units',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
